services:
  server:
    build: bittan
    ports:
      - '8000:8000'
    volumes: 
      - ./bittan:/bittan
    depends_on:
      - postgres
    container_name: bittan_server
  postgres:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bittan_db 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    container_name: bittan_postgres
