# Generated by Django 5.0 on 2024-03-14 21:04

import bittan.models.swish_payment_request
import django_enumfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bittan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwishPaymentRequest',
            fields=[
                ('time_created', models.DateTimeField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('status', django_enumfield.db.fields.EnumField(enum=bittan.models.swish_payment_request.PaymentStatus)),
                ('errorCode', django_enumfield.db.fields.EnumField(enum=bittan.models.swish_payment_request.PaymentErrorCode, null=True)),
                ('amount', models.IntegerField()),
                ('external_uri', models.TextField(null=True)),
                ('swish_token', models.TextField(null=True)),
                ('swish_request_data', models.TextField(null=True)),
            ],
        ),
    ]
