# Generated by Django 5.0 on 2025-03-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bittan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='time_paid',
        ),
    ]
