# Generated by Django 5.0 on 2024-11-22 21:03

import bittan.models.swish_payment_request
import django_enumfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bittan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwishPaymentRequestModel',
            fields=[
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('status', django_enumfield.db.fields.EnumField(default=3, enum=bittan.models.swish_payment_request.PaymentStatus)),
                ('error_code', django_enumfield.db.fields.EnumField(enum=bittan.models.swish_payment_request.PaymentErrorCode, null=True)),
                ('amount', models.IntegerField()),
                ('external_uri', models.TextField(null=True)),
                ('token', models.TextField(null=True)),
                ('swish_api_response', models.TextField(null=True)),
            ],
        ),
    ]
