# Generated by Django 5.0 on 2024-11-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bittan', '0002_swishpaymentrequestmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterevent',
            name='event_at',
        ),
        migrations.RemoveField(
            model_name='swishpaymentrequestmodel',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='times_used',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='price_currency',
        ),
        migrations.AddField(
            model_name='chapterevent',
            name='swish_message',
            field=models.TextField(default='Hej på dig du', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickettype',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='swish_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='external_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.IntegerField(),
        ),
    ]
