# Generated by Django 5.0 on 2024-03-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bittan', '0002_swishpaymentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='time_created',
        ),
    ]
