# Generated by Django 5.0 on 2024-09-19 17:04

import bittan.models.swish_payment_request
import datetime
import django_enumfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bittan', '0003_remove_ticket_time_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwishPaymentRequestModel',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('status', django_enumfield.db.fields.EnumField(default=3, enum=bittan.models.swish_payment_request.PaymentStatus)),
                ('error_code', django_enumfield.db.fields.EnumField(enum=bittan.models.swish_payment_request.PaymentErrorCode, null=True)),
                ('amount', models.IntegerField()),
                ('external_uri', models.TextField(null=True)),
                ('token', models.TextField(null=True)),
                ('swish_api_response', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SwishPaymentRequest',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='time_created',
            new_name='expires_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='telephone_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total_price_currency',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='reservation_duration',
        ),
        migrations.AddField(
            model_name='chapterevent',
            name='reservation_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.TextField(choices=[('RESERVED', 'Reserved'), ('PAID', 'Paid'), ('FAILED_EXPIRED_RESERVATION', 'Failed Expired Reservation'), ('FAILED_ADMIN', 'Failed Admin')]),
        ),
    ]
