# Generated by Django 5.1.2 on 2024-11-03 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bittan', '0004_swishpaymentrequestmodel_delete_swishpaymentrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swishpaymentrequestmodel',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
