import React from 'react';
import { useLocation, useParams } from "react-router-dom";
import { getQuestionSummary } from '../../api/questionSummary';
import { useEffect, useState } from 'react'

// This component is completely generated by AI
const CombinationTable = ({ data }) => {
  return (
    <table style={{ borderCollapse: "collapse", width: "100%" }}>
      <thead>
        <tr>
          <th style={thStyle}>Combination Names</th>
          <th style={thStyle}>Count</th>
        </tr>
      </thead>
      <tbody>
        {data.map((row, index) => {
          const ids =
            row.combination_ids?.filter(Boolean).join(", ") || "—";

          const names =
            row.combination_names?.filter(Boolean).join(", ") || "—";

          return (
            <tr key={index}>
              <td style={tdStyle}>{names}</td>
              <td style={tdStyle}>{row.combination_count}</td>
            </tr>
          );
        })}
      </tbody>
    </table>
  );
};

// AI Generated 
const thStyle = {
  border: "1px solid #ccc",
  padding: "8px",
  textAlign: "left",
  backgroundColor: "#f5f5f5",
};

// AI Generated 
const tdStyle = {
  border: "1px solid #ccc",
  padding: "8px",
};


const QuestionSummary = () => {
  const params = useParams();
  const [quesitonCombinations, setQuestionCombinations] = useState();

  useEffect(() => {
    getQuestionSummary(params.question_id).then((d) => { setQuestionCombinations(d); console.log(d) });
  }, [params])

  return (
    <div>
      <h1>This is question summary</h1>

      {quesitonCombinations ? <CombinationTable data={quesitonCombinations} /> : <>Loading....</>}
      {/* {quesitonCombinations ? (<>Loading</>) : <CombinationTable data={quesitonCombinations} />} */}
      <>{params.question_id}</>
    </div>
  );
};

export default QuestionSummary;
